version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '07:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 13.x'
      - dependency-name: electron
        versions:
          - '>= 11.x'
      - dependency-name: electron-builder
        versions:
          - '>= 21.x'
  - package-ecosystem: npm
    directory: '/app-config'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    versioning-strategy: increase
