version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '05:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    versioning-strategy: increase
    ignore:
      # don't perform major updates for electron automatically
      - dependency-name: electron
        update-types: ['version-update:semver-major']
      # don't perform major updates for the used node version as it is defined by the used electron version
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      # multiple setup problems and 4.x works fine
      - dependency-name: husky
        versions:
          - '> 4.x'
      # these are being updated to esm modules after these versions and electron doesn't currently natively support it
      # TODO: electron 28 now supports esm, so we can remove this ignore
      - dependency-name: image-type
        versions:
          - '> 4.x'
      - dependency-name: electron-dl
        versions:
          - '> 4.x'
      - dependency-name: globby
        versions:
          - '> 11.x'
      - dependency-name: uuidjs
        versions:
          - '> 4.x'
      # when building, we receive this error with winstaller 5.0:
      # Error: no such file or directory, copyfile 'vendor/7z-ia32.exe' -> 'vendor/7z.exe'
      - dependency-name: electron-winstaller
        versions:
          - '> 4.x'
      - dependency-name: eslint-plugin-no-unsanitized
        versions:
          - '> 4.0.x'
  - package-ecosystem: npm
    directory: '/app-config'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    versioning-strategy: increase

  # Github actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 99
    schedule:
      interval: 'daily'
  # Docker
  - package-ecosystem: 'docker'
    directory: '/'
    open-pull-requests-limit: 99
    schedule:
      interval: 'daily'
