version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 99
    versioning-strategy: increase
    ignore:
      - dependency-name: electron
        versions:
          - '>= 13.x'
      - dependency-name: electron-builder
        versions:
          - '>= 21.x'
      - dependency-name: husky
        versions:
          - '>= 5.x'
      - dependency-name: electron-winstaller
        versions:
          - '>= 5.x'
  - package-ecosystem: npm
    directory: '/app-config'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    versioning-strategy: increase
