version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 99
    versioning-strategy: increase
    ignore:
      # our current Electron version uses Node.js 14
      - dependency-name: '@types/node'
        versions:
          - '>= 15.x'
      # in progress, always takes some time to follow all breaking changes
      - dependency-name: electron
        versions:
          - '>= 13.x'
      - dependency-name: electron-builder
        versions:
          - '>= 21.x'
      # multiple setup problems and 4.x works fine
      - dependency-name: husky
        versions:
          - '>= 5.x'
      # when building, we receive this error with winstaller 5.0:
      # Error: no such file or directory, copyfile 'vendor/7z-ia32.exe' -> 'vendor/7z.exe'
      - dependency-name: electron-winstaller
        versions:
          - '>= 5.x'
  - package-ecosystem: npm
    directory: '/app-config'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    versioning-strategy: increase
