name: Download translations

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 6 * * *'

jobs:
  download_translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download translations
        uses: crowdin/github-action@1.0.9
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CROWDIN_PROJECT_ID: 342373
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          skip_untranslated_files: false
          # Download translations with pushing to branch
          push_translations: true
          commit_message: 'chore: Update translations'
          localization_branch_name: 'chore/update-translations'
          create_pull_request: true
          pull_request_title: 'chore: Update translations'
          token: ${{ secrets.CROWDIN_TOKEN }}
          source: '/electron/locale/en-US.json'
          translation: '/electron/locale/%locale%.json'
          base_path: '.'
